Repository ucsb-cs156-f24/proj-happycows-f24-09, pull requests merged in 2024-11, with the labels that each got.

#11 UI FIX On Inconsistent Capitalization
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/components/Commons/ManageCowsModal.js
  frontend/src/tests/components/Commons/ManageCows.test.js
  frontend/src/tests/components/Commons/ManageCowsModal.test.js
Labels: 5

#12 Tom bug profits table
  frontend/src/main/components/Commons/PagedProfitsTable.js
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
Labels: 5, Merge Candidate-CI

#35 NM - corrected footer link
  frontend/src/main/components/Nav/Footer.js
Labels: 5, Merge Candidate-CI

#34 NM - formatted buy and sell neater ticket #6
  frontend/src/main/components/Commons/ManageCows.js
Labels: 5, Merge Candidate-CI

#50 TOM - COURSES (BACKEND) GET ALL & POST API FINISH
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CoursesController.java
  src/main/resources/db/migration/changes/Courses.json
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CoursesControllerTests.java
Labels: 10

#25 Alec - Fixed Leaderboard sorting by total wealth
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
Labels: 5

#41 Alec - Added Students Database Table
  src/main/java/edu/ucsb/cs156/happiercows/entities/Students.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/StudentsRepository.java
  src/main/resources/db/migration/changes/Students.json
Labels: 5, f24-09

#43 Alec - Added PUT (edit) functionality to Students
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
  src/main/resources/db/migration/changes/Students.json
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
Labels: 10, Merge Candidate-CI, f24-09

#44 Alec - Added Delete Functionality to Students
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
Labels: 10, Merge Candidate-CI, f24-09

#52 Alec - Added Students Form
  frontend/src/fixtures/studentsFixtures.js
  frontend/src/main/components/Students/StudentsForm.js
  frontend/src/stories/components/Students/StudentsForm.stories.js
  frontend/src/tests/components/Students/StudentsForm.test.js
Labels: 10, Merge Candidate-CI, f24-09

#53 Alec - Added Students Table
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Students/StudentsTable.js
  frontend/src/main/pages/StudentsCreatePage.js
  frontend/src/main/pages/StudentsEditPage.js
  frontend/src/main/pages/StudentsIndexPage.js
  frontend/src/main/utils/studentsUtils.js
  frontend/src/stories/components/Students/StudentsTable.stories.js
  frontend/src/tests/components/Students/StudentsTable.test.js
  frontend/src/tests/pages/StudentsCreatePage.test.js
  frontend/src/tests/pages/StudentsEditPage.test.js
  frontend/src/tests/pages/StudentsIndexPage.test.js
  frontend/src/tests/utils/studentsUtils.test.js
Labels: 10, Ready-For-Staff, Merge Candidate-CI, f24-09

#59 Alec - Added test to verify correct Leaderboard sorting by total wealth
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: 5, Ready-For-Staff, Merge Candidate-CI, f24-09

#55 Tom - Add GET (show) endpoint for a single record in Courses table
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Courses.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CoursesControllerTests.java
Labels: 10, Merge Candidate-CI, f24-09

#63 Elijah - Added an Integration test for creating a new commons when you are an Admin
  src/test/java/edu/ucsb/cs156/happiercows/integration/CommonsIT.java
Labels: 10, Merge Candidate-CI, f24-09

#72 Elijah - Fixed Profit Table right aligment
  frontend/src/main/components/Commons/PagedProfitsTable.js
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
Labels: 10, Merge Candidate-CI, f24-09
