Repository ucsb-cs156-f24/proj-happycows-f24-09, pull requests merged in 2024-12, with the labels that each got.

#54 Alec - Added Index Page for Students
  frontend/.gitignore
  frontend/src/main/pages/StudentsIndexPage.js
  frontend/src/stories/pages/StudentsIndexPage.stories.js
  frontend/src/tests/pages/StudentsIndexPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
Labels: 10, f24-09

#74 fix the profit table skryker expectaiton
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
  frontend/src/tests/components/Commons/ProfitsTable.test.js
Labels: 10

#73 Neil - Announcement Form and fixes
  frontend/src/main/components/Announcement/AnnouncementForm.js
  frontend/src/main/pages/AdminAnnouncementsPage.js
  frontend/src/main/pages/AdminCreateAnnouncementsPage.js
  frontend/src/tests/components/Announcement/AnnouncementsForm.test.js
  frontend/src/tests/pages/AdminAnnouncementsPage.test.js
  frontend/src/tests/pages/AdminCreateAnnouncementsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: Ready-For-Staff, f24-09

#64 Hongtao Add Update (Put) for a single record in Course table
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CoursesControllerTests.java
Labels: 10

#57 Alec - Added Edit Page for students
  frontend/src/main/components/Students/StudentsEditForm.js
  frontend/src/main/pages/StudentsEditPage.js
  frontend/src/stories/components/Students/StudentsEditForm.stories.js
  frontend/src/stories/pages/StudentsEditPage.stories.js
  frontend/src/tests/components/Students/StudentsEditForm.test.js
  frontend/src/tests/pages/StudentsEditPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
Labels: Ready-For-Staff, f24-09

#58 Alec - Added Create Students page
  frontend/src/main/pages/StudentsCreatePage.js
  frontend/src/main/pages/StudentsIndexPage.js
  frontend/src/stories/pages/StudentsCreatePage.stories.js
  frontend/src/tests/pages/StudentsCreatePage.test.js
Labels: 10, Ready-For-Staff, Merge Candidate-CI, f24-09
